### PR TITLE
Support for viewing serialized objects

### PR DESCRIPTION
**Pull request by fullstack-zhangpeng**

### CODE REVIEW

**Comment by NSExceptional** [comment]
Wouldn't it make more sense to just deserialize the object and present an object explorer screen?

**Comment by fullstack-zhangpeng** [comment]
> Wouldn't it make more sense to just deserialize the object and present an object explorer screen? I do like the idea of being able to deserialize objects like this though.

Thx~

**Comment by NSExceptional** [comment]
I'll merge it whenever you have that ready!

**Comment by fullstack-zhangpeng** [comment]
I'm ready. What do I need to do?

**Comment by NSExceptional** [comment]
Adjust your code to present an object explorer screen of the deserialized object instead of a JSON representation of the object, and push it to your fork

**Comment by fullstack-zhangpeng** [comment]
Done.Thx~

**Comment by NSExceptional** [comment]
Did you `git push` it? There are no new changes listed

**Comment by fullstack-zhangpeng** [comment]
I have modified it and submitted it. Please check it

**Comment by NSExceptional** [comment]
Not quite what I meant, unless you forgot to push your changes; it looked like you just rebased your old changes on top of everything I've merged since you opened the PR.

Anyway, I went ahead and made the changes and pushed them to your branch. I forgot GitHub gives you the option to let me edit your fork.

Merged! Go try it out, look for `Bob.plist` in the `Documents` folder in the file browser.

**Pull request merged**
