### PR TITLE
Show copy-ready address of inspected object

### PR DESCRIPTION
**Pull request by DrBreen**
* When inspecting object, show it's memory address even if description if not available
* Allow copying this address in the same manner as object description

### CODE REVIEW

**Comment by DrBreen** [comment]
Pardon my debugging message in dealloc method.

**Comment by NSExceptional** [comment]
Could you post a screenshot of what it looks like?

**Comment by DrBreen** [comment]
Sure, of course!

**Comment by DrBreen** [comment]
This is how it looks like in the object inspector. "Copy" tooltip appears on long press, just like with "Description" field

**Comment by NSExceptional** [comment]
What do you think of this?

**Comment by DrBreen** [comment]
That's a great idea! I love it, much cleaner solution.

**Pull request merged**
