### PR TITLE
Add toolbar position persistence

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by ryanolsonk** [comment]
cool!

**Comment by AnthoPakPak** [comment]
Has it been removed from current version ?

**Comment by matrush** [comment]
@AnthoPakPak It shouldn't be, did you find any issues on the current version?

**Comment by AnthoPakPak** [comment]
@matrush Oh, indeed I was getting Flex through Cocoapods, and copy/paste the line in the Readme
`pod 'FLEX', '~> 2.0', :configurations => ['Debug']`
but it seems that the current version is 2.4, so I think this version will have this code included :)

**Pull request merged**
