### PR TITLE
feat: added ability to be compiled under project with extensions

### PR DESCRIPTION
**Pull request by tjerwinchen**
`UIApplication.sharedApplication` cannot be compiled under project with extension targets, so I make a tiny fix on this.

### CODE REVIEW

**Comment by NSExceptional** [comment]
What's the compilation error? Is that API unavailable in extensions? 😯

**Comment by tjerwinchen** [comment]
Yes, UIApplication.sharedApplication is unavailable in extensions. 😂

**Comment by tjerwinchen** [comment]
I found that in iOS 13, when a `presentationController` like  `FLEXGlobalsTableViewController` and `FLEXHierarchyTableViewController` dismissing with a swipe, `resignKeyAndDismissViewControllerAnimated:BOOL:completion` cannot get called. This will cause a bug because `keywindow` is not set back.  I make a tiny fix on this.

**Comment by NSExceptional** [comment]
I have fixed this in the 4.0 branch on my fork, take a look

**Comment by NSExceptional** [comment]
(Haven't gotten around to merging this PR yet but I will)

**Comment by NSExceptional** [comment]
With your permission, I would like to refactor this PR into a compile-time check using preprocessor directives. I have my code ready to push to your fork and merge.

Unfortunately, Xcode does not provide a preprocessor variable to detect whether the target is an extension, so we will have to instruct users to add a define for `FLEX_TARGET_IS_EXTENSION` in their project settings.

What are your thoughts?

**Pull request closed without merging**
